apiVersion: batch/v1
kind: CronJob
metadata:
  name: opensearch-index-build-logs
  namespace: custom
spec:
  schedule: "0 0 1-31/2 * *"  # Run every other day
  concurrencyPolicy: Forbid
  activeDeadlineSeconds: 86400 # terminate any running job after 1 day
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: opensearch-index-build-logs
            image: ghcr.io/spack/opensearch-index-build-logs:0.0.3
            imagePullPolicy: Always
            env:
            - name: OPENSEARCH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-endpoint
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: opensearch-password
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab-token
            - name: GITLAB_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab_pg_host
            - name: GITLAB_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab_pg_port
            - name: GITLAB_PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab_pg_dbname
            - name: GITLAB_PG_USER
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab_pg_user
            - name: GITLAB_PG_PASS
              valueFrom:
                secretKeyRef:
                  name: opensearch-index-build-logs
                  key: gitlab_pg_pass
          nodeSelector:
            spack.io/node-pool: base
