apiVersion: v1
kind: Secret
metadata:
  name: gitlab-omniauth-github
  namespace: gitlab
stringData:
  provider: |
    {
      "name": "github",
      "app_id": "id",
      "app_secret": "secret"
    }
