version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: "-Xms250m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
    ports:
      - ${DOCKER_OPENSEARCH_PORT-9200}:9200
      - ${DOCKER_OPENSEARCH_PORT-9300}:9300

  redis:
    image: redis:latest
    ports:
      - ${DOCKER_REDIS_PORT-6379}:6379

  prometheus:
    image: prom/prometheus:latest
    ports:
      - ${DOCKER_PROMETHEUS_PORT-9090}:9090

  gitlab-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - gitlab-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab

  minio:
    image: minio/minio:latest
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data", "--console-address", ":${DOCKER_MINIO_CONSOLE_PORT-9001}"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
      - ${DOCKER_MINIO_CONSOLE_PORT-9001}:9001
    volumes:
      - minio:/data

  gitlab:
    image: zengxs/gitlab:ee
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        registry_external_url 'http://gitlab:5050'
        gitlab_rails['db_host'] = 'gitlab-db'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
    depends_on:
      - gitlab-db

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2375
      # Use the host's network interface instead of the Docker one.
      # Note, gitlab-runner runs jobs inside docker, but is itself deployed
      # in a docker container. So the "host" in this case actually refers to the
      # `gitlab-runner` docker container defined in this docker-compose.yaml.
      DOCKER_NETWORK_MODE: host

  dind:
    image: docker:20-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2

volumes:
  postgres:
  minio:
  gitlab:
  gitlab-db:
