apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../production/custom/gitlab-setting-updater/cronjobs.yaml
  - ../../production/custom/gitlab-setting-updater/serviceaccounts.yaml
