---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-share-controller
  namespace: gitlab

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-share-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["create", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["patch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-share-controller
subjects:
  - kind: ServiceAccount
    name: node-share-controller
    namespace: gitlab
roleRef:
  kind: ClusterRole
  name: node-share-controller
  apiGroup: rbac.authorization.k8s.io
