# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: slack-webhook-alertmanager
#   namespace: monitoring
#   annotations:
#       kustomize.toolkit.fluxcd.io/reconcile: disabled
# data:
#   webhook: DEADBEEF  # fake-secret

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     kustomize.toolkit.fluxcd.io/reconcile: disabled
#   name: kube-prometheus-stack-grafana
#   namespace: monitoring
# data:
#   admin-password: DEADBEEF # fake-secret
#   admin-user: DEADBEEF # fake-secret
#   ldap-toml: ""

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     kustomize.toolkit.fluxcd.io/reconcile: disabled
#   name: grafana-github-oauth-client
#   namespace: monitoring
# data:
#   client-id: DEADBEEF # fake-secret
#   client-secret: DEADBEEF # fake-secret

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-additional-datasources
#   namespace: monitoring
#   annotations:
#     kustomize.toolkit.fluxcd.io/reconcile: disabled
# stringData:
#   values.yaml: |
#     grafana:
#       additionalDataSources:
#         - name: OpenSearch
#           editable: "false"
#           type: grafana-opensearch-datasource
#           url: DEADBEEF # fake value
#           version: "1"
#           access: proxy
#           basicAuth: "true"
#           basicAuthUser: DEADBEEF # fake value
#           secureJsonData:
#             basicAuthPassword: DEADBEEF # fake value
#           jsonData:
#             database: "gitlab-job-failures-*"
#             timeField: timestamp
#             flavor: opensearch
#             version: "1.3.0"
