apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: spack-gateway
  namespace: aws-application-networking-system
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.spack.io"
      allowedRoutes:
        namespaces:
          from: All
      # tls:
      #   mode: Terminate
      #   certificateRefs:
      #     # AWS controller ignores this; set tls.options["application-networking.k8s.aws/certificate-arn"] to your ACM cert ARN for TLS.
      #     - kind: Secret
      #       name: tls-cdash
      #       group: ""
