apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: spack-gateway
  namespace: aws-application-networking-system
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.spack.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-cdash
            group: ""
