---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: "true"
  name: spack-signing-runner-secret
  namespace: gitlab
data:
  runner-token: ""
  # Token from: https://gitlab.spack.io/scott/pipeline-experiments/
  runner-registration-token: "DEADBEEF=="
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    fluxcd.io/ignore: "true"
  name: spack-signing-key-encrypted
  namespace: pipeline
data:
  # base64 encoded, KMS data-key encrypted, private signing key.
  signing_key.encrypted.gpg: |-
    DEADBEEF==

  # base64 encoded public key for the reputational signing key.
  signing_key_public.gpg: |-
    DEADBEEF==
  # base64 encoded, public key of the intermediate CI key for verifying before resigning
  intermediate_ci_public_key.gpg: |-
    DEADBEEF==
