apiVersion: apps/v1
kind: Deployment
metadata:
  name: builds-spack-io-db
  namespace: spack
  labels:
    app: builds-spack-io
    svc: postgres

spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: builds-spack-io-db
      svc: postgres

  template:
    metadata:
      labels:
        app: builds-spack-io-db
        svc: postgres

    spec:

      nodeSelector:
        spack.io/node-pool: base
      containers:
        - name: builds-spack-io-db
          image: postgres:13.3
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data          
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spack-build-credentials
                  key: database_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: spack-build-credentials
                  key: database_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: spack-build-credentials
                  key: database_name
          ports:
            - name: tcp-postgres
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

      volumes:
        - name: postgres-disk
          persistentVolumeClaim:
            claimName: builds-spack-io-database
