apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builds-spack-io-db
  namespace: spack
  labels:
    app: builds-spack-io-db
    svc: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
