apiVersion: v1
kind: Service
metadata:
  name: build
  namespace: spack
  labels:
    app: builds-spack-io-db
    svc: postgres
spec:
  selector:
    app: builds-spack-io-db
  type: ClusterIP
  ports:
      # tcp-postgres
    - port: 5432
      targetPort: 5432
