apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab-error-processor
  namespace: custom
  annotations:
    fluxcd.io/ignore: "true"
stringData:
  opensearch-endpoint: The endpoint of the opensearch API. Should be the same as the "host" from k8s/logging/secrets.yaml
  opensearch-username: Admin user name for the OpenSearch cluster. Set using the AWS console.
  opensearch-password: Password for the admin account of the OpenSearch cluster. Set using the AWS console.
  gitlab-token: GitLab personal access token with read access to spack/spack repo
