- op: replace
  path: /metadata/name
  value: glr-x86-64-v4
# Apply label for highest supported x86_64 microarch version (v4)
- op: add
  path: /spec/template/metadata/labels/spack.io~1x86_64
  value: "v4"
# Require amd64 nodes
- op: add
  path: /spec/template/spec/requirements/-
  value:
    key: "kubernetes.io/arch"
    operator: In
    values: ["amd64"]
# Only provision nodes from instance families that have been verified
# to support x86_64_v4 by archspec.
- op: add
  path: /spec/template/spec/requirements/-
  value:
    key: "karpenter.k8s.aws/instance-family"
    operator: In
    values:
      - "c5"
      - "c5n"
      - "c6i"
      - "m5"
      - "m5n"
      - "m5zn"
      - "m6i"
      - "r5"
      - "r5b"
      - "r5n"
      - "r6i"
      - "t3"
      - "x2iedn"
      - "x2iezn"
