---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-cdash
  namespace: cdash
spec:
  secretName: tls-cdash
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: cdash.next.spack.io
  dnsNames:
  - cdash.next.spack.io
