---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdash
  namespace: cdash
  labels:
    app: cdash
    svc: web
spec:
  selector:
    matchLabels:
      app: cdash
      svc: web
  replicas: 1
  template:
    metadata:
      labels:
        app: cdash
        svc: web
    spec:
      restartPolicy: Always
      containers:
      - name: cdash
        command: ["/bin/bash", "-c"]
        args:
          - >
            eval 'CDASH_CONFIG="$(CDASH_CONFIG_TEMPLATE)"' ;
            export CDASH_CONFIG ;
            exec /bin/bash /docker-entrypoint.sh
        image: kitware/cdash:spack_deploy_v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
        env:
        - name: CDASH_ROOT_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: root-password
        - name: CDASH_DB_HOST
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-host
        - name: CDASH_DB_TYPE
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-type
        - name: CDASH_DB_NAME
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-name
        - name: CDASH_DB_LOGIN
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-login
        - name: CDASH_DB_PORT
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-port
        - name: CDASH_DB_PASS
          valueFrom:
            secretKeyRef:
              name: cdash-secrets
              key: db-password
        - name: CDASH_CONFIG_TEMPLATE
          value: |
            \$CDASH_DB_HOST = '\'$CDASH_DB_HOST\'';
            \$CDASH_DB_NAME = '\'$CDASH_DB_NAME\'';
            \$CDASH_DB_TYPE = '\'$CDASH_DB_TYPE\'';
            \$CDASH_DB_LOGIN = '\'$CDASH_DB_LOGIN\'';
            \$CDASH_DB_PORT = '\'$CDASH_DB_PORT\'';
            \$CDASH_DB_PASS = '\'$CDASH_DB_PASS\'';
            \$CDASH_DB_CONNECTION_TYPE = '\'host\'';
            \$CDASH_BASE_URL = '\'https://cdash.spack.io\'';
            \$CDASH_USE_HTTPS = '\'1\'';
            \$CDASH_PRODUCTION_MODE = '\'1\'';
            \$CDASH_AUTOREMOVE_BUILDS = '\'1\'';
            \$CDASH_ACTIVE_PROJECT_DAYS = '\'0\'';
            \$CDASH_ASYNCHRONOUS_SUBMISSION = '\'1\'';
      nodeSelector:
        spack.io/node-pool: base
