---
apiVersion: v1
kind: Secret
metadata:
  name: cdash-secrets
  namespace: cdash
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  root-password: ZmFrZS1zZWNyZXQK  # fake-secret
  db-host: ZmFrZS1zZWNyZXQK  # fake-secret
  db-type: ZmFrZS1zZWNyZXQK  # fake-secret
  db-name: ZmFrZS1zZWNyZXQK  # fake-secret
  db-login: ZmFrZS1zZWNyZXQK  # fake-secret
  db-port: ZmFrZS1zZWNyZXQK  # fake-secret
  db-password: ZmFrZS1zZWNyZXQK  # fake-secret
