---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: aws-efs-csi-driver
      version: 2.2.0  # aws-efs-csi-driver@1.3.4
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
  values:
    image:
      repository: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-efs-csi-driver
    controller:
      nodeSelector:
        spack.io/node-pool: base
      serviceAccount:
        create: false
        name: efs-csi-controller-sa
