---
# Provisioner for graviton3 gitlab runners
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: pcluster-amzn2-glr-graviton3
spec:
  providerRef:
    name: pcluster-amzn2-arm64

  # Terminate nodes after 5 minutes of idle time
  ttlSecondsAfterEmpty: 300

  # Resource limits for this provisioner only
  limits:
    resources:
      cpu: 3840 # 16 vCPUs * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)
      memory: 15Ti # 64 Gi * 6 replicas * 20 concurrent jobs * 2 runners (public & protected)

  requirements:
    # Only spin up arm64 nodes
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]

    # Only provision nodes with graviton3 processors.
    # Data gleaned from https://aws.amazon.com/ec2/graviton/
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values:
        - "c7g"
        - "m7g"
        - "r7g"

    # Instance Size
    - key: "karpenter.k8s.aws/instance-size"
      operator: In
      values:
        - "medium"
        - "large"
        - "xlarge"
        - "2xlarge"
        - "3xlarge"
        - "4xlarge"
        - "6xlarge"
        - "8xlarge"
        - "10xlarge"
        - "12xlarge"
        - "16xlarge"

    # Availability Zones
    - key: "topology.kubernetes.io/zone"
      operator: In
      values:
      - "us-west-1b"
      - "us-west-1c"
      # values:
      #   - "us-east-1a"
      #   - "us-east-1b"
      #   - "us-east-1c"
      #   - "us-east-1d"

    # Only use spot instances for runners
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]

  # Only provision nodes for pods specifying the glr-graviton3 node pool
  labels:
    spack.io/node-pool: pcluster-amzn2-glr-graviton3
    spack.io/pipeline: "true"
