---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lazy-gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
