---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spackbot-spack-io
  namespace: spack
spec:
  tls:
  - secretName: tls-spackbot
  rules:
  - host: spackbot.spack.io
    http:
      paths:
      - backend:
          service:
            name: spackbot-spack-io
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
