---
apiVersion: v1
kind: Secret
metadata:
  name: spack-bot-credentials
  namespace: spack
  annotations:
    fluxcd.io/ignore: "true"
  labels:
    app: spackbot-spack-io
    svc: web
data:
  gitlab_token: |
    # result of:
    echo -n ${gitlab_token} | base64
  github_webhook_secret: |
    # result of:
    echo -n ${gitlab_webhook_secret} | base64
  github_private_key: |
    # result of doing this to github private key download:
    cat ~/Downloads/spack-bot.2021-07-14.private-key.pem  | perl -pe 's/\n/\\n/;' | perl -pe 's/\\n$/\n/;' | base64
    # note that you can leave the newlines in the base64 encoded output -- k8s understands them.
