---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spackbotdev-spack-io
  namespace: spack
  labels:
    app: spackbotdev-spack-io
    svc: web
spec:
  selector:
    matchLabels:
      app: spackbotdev-spack-io
      svc: web
  replicas: 1
  template:
    metadata:
      labels:
        app: spackbotdev-spack-io
        svc: web
    spec:
      containers:
      - name: web
        image: "ghcr.io/spack/spack-bot:latest"
        # Can use some other image for testing, see README.md
        #image: "ghcr.io/kwryankrattiger/spackbot:0.0.1"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 110m
            memory: 200M
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SPACKBOT_LOG_LEVEL
          value: "DEBUG"
        - name: REDIS_HOST
          value: pr-binary-graduation-task-queue.cev8lh.ng.0001.use1.cache.amazonaws.com
        - name: REDIS_PORT
          value: "6379"
        - name: PR_BINARIES_MIRROR_BASE_URL
          value: "s3://spack-binaries-prs/testing"
        - name: SHARED_PR_BINARIES_RETIRE_AFTER_DAYS
          value: "9999"
        - name: TASK_QUEUE_SHORT
          value: "tasksdevelop"
        - name: TASK_QUEUE_LONG
          value: "tasksdevelop_ltask"
        - name: WORKER_JOB_TIMEOUT
          value: "600"
        - name: GITLAB_SPACK_PROJECT_URL
          value: https://gitlab.spack.io/api/v4/projects/23
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GITHUB_APP_IDENTIFIER
          value: "126480"
        - name: GITHUB_APP_REQUESTER
          value: "spack-test"
        - name: SPACKBOT_NAME
          value: "@spackbot-test"
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: gitlab_token
        - name: GITHUB_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_private_key
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_webhook_secret
      nodeSelector:
        spack.io/node-pool: base

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spackbotdev-workers
  namespace: spack
  labels:
    app: spackbotdev-workers
    svc: workers
spec:
  selector:
    matchLabels:
      app: spackbotdev-workers
      svc: workers
  replicas: 1
  template:
    metadata:
      labels:
        app: spackbotdev-workers
        svc: workers
    spec:
      serviceAccountName: spackbotdev-spack-io
      containers:
      - name: worker
        image: "ghcr.io/spack/spackbot-workers:latest"
        # Can use some other image for testing, see README.md
        #image: "ghcr.io/kwryankrattiger/spackbot-workers:0.0.1"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 900m
            memory: 1G
        # Mount secrets to non-existing location
        volumeMounts:
        - mountPath: "/git_rsa"
          name: spack-bot-dev-idrsa
          readOnly: true
        env:
        - name: PR_BINARIES_MIRROR_BASE_URL
          value: "s3://spack-binaries-prs/testing"
        - name: SHARED_PR_BINARIES_RETIRE_AFTER_DAYS
          value: "9999"
        - name: SPACKBOT_LOG_LEVEL
          value: "DEBUG"
        - name: REDIS_HOST
          value: pr-binary-graduation-task-queue.cev8lh.ng.0001.use1.cache.amazonaws.com
        - name: REDIS_PORT
          value: "6379"
        - name: TASK_QUEUE_SHORT
          value: "tasksdevelop"
        - name: TASK_QUEUE_LONG
          value: "tasksdevelop_ltask"
        - name: WORKER_TASK_QUEUE
          value: "tasksdevelop"
        - name: WORKER_JOB_TIMEOUT
          value: "600"
        - name: GITLAB_SPACK_PROJECT_URL
          value: https://gitlab.spack.io/api/v4/projects/23
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GITHUB_APP_IDENTIFIER
          value: "126480"
        - name: GITHUB_APP_REQUESTER
          value: "spack-test"
        - name: SPACKBOT_NAME
          value: "@spackbot-test"
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: gitlab_token
        - name: GITHUB_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_private_key
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_webhook_secret
      volumes:
      - name: spack-bot-dev-idrsa
        secret:
          secretName: spack-bot-dev-idrsa
          defaultMode: 0600
      nodeSelector:
        spack.io/node-pool: base

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spackbotdev-lworkers
  namespace: spack
  labels:
    app: spackbotdev-lworkers
    svc: workers
spec:
  selector:
    matchLabels:
      app: spackbotdev-lworkers
      svc: workers
  # replicas cannot exceed 1 until
  # rq jobs can be properly sync'd
  replicas: 1
  template:
    metadata:
      labels:
        app: spackbotdev-lworkers
        svc: workers
    spec:
      serviceAccountName: spackbotdev-spack-io
      containers:
      - name: long-task-worker
        image: "ghcr.io/spack/spackbot-workers:latest"
        # Can use some other image for testing, see README.md
        #image: "ghcr.io/kwryankrattiger/spackbot-workers:0.0.1"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 900m
            memory: 1G
        # Mount secrets to non-existing location
        volumeMounts:
        - mountPath: "/git_rsa"
          name: spack-bot-dev-idrsa
          readOnly: true
        env:
        - name: PR_BINARIES_MIRROR_BASE_URL
          value: "s3://spack-binaries-prs/testing"
        - name: SHARED_PR_BINARIES_RETIRE_AFTER_DAYS
          value: "9999"
        - name: SPACKBOT_LOG_LEVEL
          value: "DEBUG"
        - name: REDIS_HOST
          value: pr-binary-graduation-task-queue.cev8lh.ng.0001.use1.cache.amazonaws.com
        - name: REDIS_PORT
          value: "6379"
        - name: TASK_QUEUE_SHORT
          value: "tasksdevelop"
        - name: TASK_QUEUE_LONG
          value: "tasksdevelop_ltask"
        - name: WORKER_TASK_QUEUE
          value: "tasksdevelop_ltask"
        - name: WORKER_JOB_TIMEOUT
          value: "600"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GITHUB_APP_IDENTIFIER
          value: "126480"
        - name: GITHUB_APP_REQUESTER
          value: "spack-test"
        - name: SPACKBOT_NAME
          value: "@spackbot-test"
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: gitlab_token
        - name: GITHUB_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_private_key
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: spack-bot-dev-credentials
              key: github_webhook_secret
      volumes:
      - name: spack-bot-dev-idrsa
        secret:
          secretName: spack-bot-dev-idrsa
          defaultMode: 0600
      nodeSelector:
        spack.io/node-pool: base

