---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: gitlab

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: pipeline

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "secrets"]
    verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: runner
roleRef:
  kind: ClusterRole
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: pipeline
subjects:
  - kind: ServiceAccount
    name: runner
roleRef:
  kind: ClusterRole
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io
