---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-error-processor
  namespace: custom
  labels:
    app: gitlab-error-processor
    svc: web
spec:
  selector:
    matchLabels:
      app: gitlab-error-processor
      svc: web
  replicas: 2
  template:
    metadata:
      labels:
        app: gitlab-error-processor
        svc: web
    spec:
      restartPolicy: Always
      serviceAccountName: gitlab-error-processor
      containers:
      - name: gitlab-error-processor
        image: ghcr.io/spack/gitlab-error-processor:0.0.3
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: python-scripts-sentry-config
        resources:
          requests:
            cpu: 350m
            memory: 1G
          limits:
            cpu: 1600m
            memory: 1G
        ports:
        - containerPort: 8080
      nodeSelector:
        spack.io/node-pool: base
