apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rotate-gitlab-aws-access-keys
  namespace: custom
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rotate-keys
          restartPolicy: Never
          containers:
          - name: rotate-gitlab-aws-access-keys
            image: spack/ci-key-rotate:0.0.2
            imagePullPolicy: IfNotPresent
            env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rotate-keys
                  key: gitlab-token
          nodeSelector:
            spack.io/node-pool: base
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clear-admin-keys
  namespace: custom
spec:
  schedule: "0 0 10 */2 *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: clear-admin-keys
          restartPolicy: Never
          containers:
          - name: clear-admin-keys
            image: spack/ci-key-clear:0.0.1
            imagePullPolicy: IfNotPresent
          nodeSelector:
            spack.io/node-pool: base
