---
apiVersion: v1
kind: Secret
metadata:
  name: rotate-keys
  namespace: custom
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  gitlab-token: "" # gitlab access token (get from https://gitlab.spack.io/spack/spack/-/settings/access_tokens)
