apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gh-gl-sync
  namespace: custom
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  github-access-token: "" # This token must have repo:status permissions
  gitlab-ssh-key: ""
