---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-webservice
  namespace: gitlab
spec:
  secretName: tls-gitlab-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.spack.io
    - gitlab.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  secretName: tls-gitlab-registry
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - registry.gitlab.spack.io
    - registry.gitlab.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  secretName: tls-gitlab-minio
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - minio.gitlab.spack.io
    - minio.gitlab.next.spack.io
