---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secrets
  namespace: fluent-bit
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
  labels:
    k8s-app: fluent-bit
type: Opaque
stringData:
  output-elasticsearch.conf: |
    [OUTPUT]
        Name             es
        Match            *
        Host             DEADBEEF  # fake value
        Port             443
        TLS              On
        AWS_Auth         On
        AWS_Region       us-east-1
        Retry_Limit      6
        Logstash_Format  On
        Logstash_Prefix  fluent-bit
        Replace_Dots     On
        Trace_Error      On
