---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: runner-large-x86-pub
  namespace: gitlab
spec:
  releaseName: large-x86-pub
  chart:
    name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.37.2  # gitlab-runner@14.7.0
  values:
    image: gitlab/gitlab-runner:alpine-v14.7.0
    imagePullPolicy: IfNotPresent

    gitlabUrl: "https://gitlab.spack.io/"
    unregisterRunners: true
    terminationGracePeriodSeconds: 21600  # six hours
    concurrent: 20
    checkInterval: 30
    # preEntrypointScript: |
    #   echo "Hello, from large-pub runner"

    metrics:
      enabled: true

    rbac:
      serviceAccountName: runner

    runners:
      config: |
        [[runners]]
          requestConcurrency =  20
          output_limit = 4096
          environment = ["FF_GITLAB_REGISTRY_HELPER_IMAGE=1"]
          [runners.kubernetes]
            privileged = false
            cpu_request = "1500m"
            namespace = "pipeline"
            poll_timeout = 600  # ten minutes
            service_account = "runner"
            [runners.kubernetes.pod_annotations]
              "gitlab/ci_pipeline_url" = "$CI_PIPELINE_URL"
              "gitlab/ci_job_url" = "$CI_JOB_URL"
              "gitlab/ci_project_url" = "$CI_PROJECT_URL"
              "gitlab/ci_runner_description" = "$CI_RUNNER_DESCRIPTION"
              "gitlab/ci_job_id" = "$CI_JOB_ID"
            [runners.kubernetes.pod_labels]
              "metrics/gitlab_ci_pipeline_id" = "$CI_PIPELINE_ID"
              "metrics/gitlab_ci_project_namespace" = "$CI_PROJECT_NAMESPACE"
              "metrics/gitlab_ci_project_name" = "$CI_PROJECT_NAME"
              "metrics/gitlab_ci_job_stage" = "$CI_JOB_STAGE"
              "metrics/gitlab_ci_commit_ref_name" = "$CI_COMMIT_REF_NAME"
              "metrics/spack_ci_stack_name" = "$SPACK_CI_STACK_NAME"
              "metrics/spack_job_spec_pkg_name" = "$SPACK_JOB_SPEC_PKG_NAME"
              "metrics/spack_spec_needs_rebuild" = "$SPACK_SPEC_NEEDS_REBUILD"
            [runners.kubernetes.node_selector]
              "kubernetes.io/arch" = "amd64"
              "spack.io/node-pool" = "glr-large-pub"

      # default image
      image: "busybox:1.32.0"
      imagePullPolicy: "if-not-present"
      locked: false

      tags: "x86_64,avx,avx2,avx512,large,public,aws,spack"
      runUntagged: false
      secret: gitlab-gitlab-runner-secret  # from gitlab release

      # Distributed runners caching
      # TODO(opadron): Look into this after setting up stand-alone minio service
      cache: {}
        ## General settings
        # cacheType: s3
        # cachePath: "gitlab_runner"
        # cacheShared: true

        ## S3 settings
        # s3ServerAddress: s3.amazonaws.com
        # s3BucketName:
        # s3BucketLocation:
        # s3CacheInsecure: false
        # secretName: s3access

        ## GCS settings
        # gcsBucketName:
        ## Use this line for access using access-id and private-key
        # secretName: gcsaccess
        ## Use this line for access using google-application-credentials file
        # secretName: google-application-credentials

      services: {}
      # cpuRequests: 50m
      # cpuLimit: 50m
      # memoryRequests: 144Mi
      # memoryLimit: 144Mi

      helpers: {}
      # cpuRequests: 50m
      # cpuLimit: 50m
      # memoryRequests: 144Mi
      # memoryLimit: 144Mi

    nodeSelector:
      spack.io/node-pool: base  # pool for the runner
