---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spack-io-updater
  namespace: spack
data:
  script: |
    #! /bin/sh -e
    date
    echo
    wget -O -                                                            \
        "https://dl.k8s.io/v1.15.0/kubernetes-client-linux-amd64.tar.gz" \
            | tar xzf -                                                  \
    echo "ROLLOUT deployments/$dep"
    exec kubernetes/client/bin/kubectl rollout restart -n spack \
        deployments/spack-io
