---
apiVersion: v1
kind: Secret
metadata:
  name: drift-server-secrets
  namespace: spack
  annotations:
      fluxcd.io/ignore: "true"
data:
  drift_server_dsn: ZmFrZS1zZWNyZXQK   # fake-secret
  drift_server_user: ZmFrZS1zZWNyZXQK  # fake-secret
  drift_server_pass: ZmFrZS1zZWNyZXQK  # fake-secret
