---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ingress-nginx/client-ca"
spec:
  tls:
  - secretName: tls-metabase
  rules:
  - host: metabase.test.spack.io
    http:
      paths:
      - backend:
          service:
            name: metabase
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
