---
# Secret used for creating the gitlab_ro_user with the gitlab_ro_user_job.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ro-postgresql-password
  namespace: gitlab
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  postgresql-gitlab-ro-user-password: DEADBEEF # fake-secret
---
# Secret used for setting up the metabase postgres instance's postgres user
# password.
apiVersion: v1
kind: Secret
metadata:
  name: metabase-postgresql-password
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  postgresql-password: DEADBEEF # fake-secret
---
# Secret used to log into the GitLab postgres instance
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgresql-secrets
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
stringData:
  gitlab-postgresql-host: DEADBEEF # fake-secret
  gitlab-postgresql-password: DEADBEEF # fake-secret
