name: test_secrets_scripts

on:
  pull_request:
    paths:
      - "secrets/*"

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Install kubeseal
        run: |
          # Fetch the latest sealed-secrets version using GitHub API
          KUBESEAL_VERSION=$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/tags | jq -r '.[0].name' | cut -c 2-)

          # Check if the version was fetched successfully
          if [ -z "$KUBESEAL_VERSION" ]; then
              echo "Failed to fetch the latest KUBESEAL_VERSION"
              exit 1
          fi

          wget "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz"
          tar -xvzf kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz kubeseal
          sudo install -m 755 kubeseal /usr/local/bin/kubeseal

          echo "Installed kubeseal $KUBESEAL_VERSION"

      - name: Install hatch
        run: pip install hatch

      - name: test
        working-directory: secrets
        run: hatch run test:test

      - name: lint
        working-directory: secrets
        run: hatch run lint:lint

  test-mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v5

      - name: Install kubeseal
        run: brew install kubeseal

      - name: Install hatch
        run: pip install hatch

      - name: test
        working-directory: secrets
        run: hatch run test:test
