name: Publish Docker Images

on:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push spack-ci-bridge
        id: docker_build_sync
        uses: docker/build-push-action@v2
        with:
          context: ./gh-gl-sync
          file: ./gh-gl-sync/Dockerfile
          push: true
          tags: zackgalbreath/spack-ci-bridge:0.0.12
      -
        name: Image digest
        run: echo ${{ steps.docker_build_sync.outputs.digest }}
  scrape:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gitlab-api-scrape
        id: docker_build_scrape
        uses: docker/build-push-action@v2
        with:
          context: ./scripts/gitlab_api
          file: ./scripts/gitlab_api/Dockerfile
          push: true
          tags: zackgalbreath/gitlab-api-scrape:0.0.2
      -
        name: Image digest
        run: echo ${{ steps.docker_build_scrape.outputs.digest }}
